/**
 * generated by Xtext 2.21.0
 */
package hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.impl;

import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.AllPackageEntry;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.AllPatternEntry;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ApplicationConfigurationFactory;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ApplicationConfigurationPackage;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ClassReference;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ClassTypeScope;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.Command;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.Config;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ConfigDeclaration;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ConfigEntry;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ConfigReference;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ConfigSpecification;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ConfigurationScript;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.CustomEntry;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.Declaration;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.DocumentLevelSpecification;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.DocumentationEntry;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.EPackageImport;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ExactNumber;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.File;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.FileDeclaration;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.FileReference;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.FileSpecification;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.FolderEntry;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.GenerationTask;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.GraphPattern;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.GraphPatternDeclaration;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.GraphPatternReference;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.Import;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.IntEnumberation;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.IntegerReference;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.IntegerScope;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.IntegerTypeScope;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.IntervallNumber;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.MemoryEntry;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.Metamodel;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.MetamodelDeclaration;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.MetamodelElement;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.MetamodelEntry;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.MetamodelReference;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.MetamodelSpecification;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ModelEntry;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.NumberSpecification;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ObjectReference;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ObjectTypeScope;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.PartialModel;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.PartialModelDeclaration;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.PartialModelEntry;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.PartialModelReference;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.PartialModelSpecification;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.PatternElement;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.PatternEntry;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.PatternSpecification;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.RealEnumeration;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.RealReference;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.RealScope;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.RealTypeScope;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.RuntimeEntry;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.Scope;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ScopeDeclaration;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ScopeReference;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ScopeSpecification;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.Solver;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.StringEnumeration;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.StringReference;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.StringScope;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.StringTypeScope;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.Task;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.TypeReference;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.TypeScope;
import hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ViatraImport;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.EcorePackage;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.eclipse.viatra.query.patternlanguage.emf.vql.PatternLanguagePackage;

import org.eclipse.xtext.common.types.TypesPackage;

import org.eclipse.xtext.xbase.XbasePackage;

import org.eclipse.xtext.xtype.XtypePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ApplicationConfigurationPackageImpl extends EPackageImpl implements ApplicationConfigurationPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass configurationScriptEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass commandEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass importEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ePackageImportEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass viatraImportEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fileSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fileDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fileReferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fileEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass metamodelSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass metamodelEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass allPackageEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass metamodelElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass metamodelDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass metamodelReferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass metamodelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass partialModelSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass partialModelEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass folderEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass partialModelDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass partialModelReferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass partialModelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass patternSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass patternEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass allPatternEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass patternElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass graphPatternDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass graphPatternReferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass graphPatternEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass configSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass configDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass configEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass documentationEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass runtimeEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass memoryEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass customEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass configReferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass configEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass scopeSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass typeScopeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass classTypeScopeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass objectTypeScopeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integerTypeScopeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass realTypeScopeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stringTypeScopeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass typeReferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass classReferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass objectReferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integerReferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass realReferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stringReferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass numberSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass exactNumberEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass intervallNumberEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass intEnumberationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass realEnumerationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stringEnumerationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass scopeDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass scopeReferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass scopeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass taskEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass generationTaskEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integerScopeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass realScopeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stringScopeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum documentLevelSpecificationEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum solverEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ApplicationConfigurationPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private ApplicationConfigurationPackageImpl()
  {
    super(eNS_URI, ApplicationConfigurationFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link ApplicationConfigurationPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static ApplicationConfigurationPackage init()
  {
    if (isInited) return (ApplicationConfigurationPackage)EPackage.Registry.INSTANCE.getEPackage(ApplicationConfigurationPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredApplicationConfigurationPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    ApplicationConfigurationPackageImpl theApplicationConfigurationPackage = registeredApplicationConfigurationPackage instanceof ApplicationConfigurationPackageImpl ? (ApplicationConfigurationPackageImpl)registeredApplicationConfigurationPackage : new ApplicationConfigurationPackageImpl();

    isInited = true;

    // Initialize simple dependencies
    EcorePackage.eINSTANCE.eClass();
    PatternLanguagePackage.eINSTANCE.eClass();
    XtypePackage.eINSTANCE.eClass();
    TypesPackage.eINSTANCE.eClass();
    XbasePackage.eINSTANCE.eClass();

    // Create package meta-data objects
    theApplicationConfigurationPackage.createPackageContents();

    // Initialize created meta-data
    theApplicationConfigurationPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theApplicationConfigurationPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(ApplicationConfigurationPackage.eNS_URI, theApplicationConfigurationPackage);
    return theApplicationConfigurationPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConfigurationScript()
  {
    return configurationScriptEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getConfigurationScript_Imports()
  {
    return (EReference)configurationScriptEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getConfigurationScript_Commands()
  {
    return (EReference)configurationScriptEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCommand()
  {
    return commandEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImport()
  {
    return importEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEPackageImport()
  {
    return ePackageImportEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEPackageImport_ImportedPackage()
  {
    return (EReference)ePackageImportEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getViatraImport()
  {
    return viatraImportEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getViatraImport_ImportedViatra()
  {
    return (EReference)viatraImportEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclaration()
  {
    return declarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDeclaration_Name()
  {
    return (EAttribute)declarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFileSpecification()
  {
    return fileSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFileSpecification_Path()
  {
    return (EAttribute)fileSpecificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFileDeclaration()
  {
    return fileDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFileDeclaration_Specification()
  {
    return (EReference)fileDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFileReference()
  {
    return fileReferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFileReference_Referred()
  {
    return (EReference)fileReferenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFile()
  {
    return fileEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMetamodelSpecification()
  {
    return metamodelSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMetamodelSpecification_Entries()
  {
    return (EReference)metamodelSpecificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMetamodelEntry()
  {
    return metamodelEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMetamodelEntry_Package()
  {
    return (EReference)metamodelEntryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAllPackageEntry()
  {
    return allPackageEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAllPackageEntry_Exclusion()
  {
    return (EReference)allPackageEntryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMetamodelElement()
  {
    return metamodelElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMetamodelElement_Classifier()
  {
    return (EReference)metamodelElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMetamodelElement_Feature()
  {
    return (EReference)metamodelElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMetamodelDeclaration()
  {
    return metamodelDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMetamodelDeclaration_Specification()
  {
    return (EReference)metamodelDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMetamodelReference()
  {
    return metamodelReferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMetamodelReference_Referred()
  {
    return (EReference)metamodelReferenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMetamodel()
  {
    return metamodelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPartialModelSpecification()
  {
    return partialModelSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPartialModelSpecification_Entry()
  {
    return (EReference)partialModelSpecificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPartialModelEntry()
  {
    return partialModelEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPartialModelEntry_Path()
  {
    return (EReference)partialModelEntryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModelEntry()
  {
    return modelEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFolderEntry()
  {
    return folderEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFolderEntry_Exclusion()
  {
    return (EReference)folderEntryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPartialModelDeclaration()
  {
    return partialModelDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPartialModelDeclaration_Specification()
  {
    return (EReference)partialModelDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPartialModelReference()
  {
    return partialModelReferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPartialModelReference_Referred()
  {
    return (EReference)partialModelReferenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPartialModel()
  {
    return partialModelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPatternSpecification()
  {
    return patternSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPatternSpecification_Entries()
  {
    return (EReference)patternSpecificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPatternEntry()
  {
    return patternEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPatternEntry_Package()
  {
    return (EReference)patternEntryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAllPatternEntry()
  {
    return allPatternEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAllPatternEntry_Exclusuion()
  {
    return (EReference)allPatternEntryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPatternElement()
  {
    return patternElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPatternElement_Pattern()
  {
    return (EReference)patternElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGraphPatternDeclaration()
  {
    return graphPatternDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGraphPatternDeclaration_Specification()
  {
    return (EReference)graphPatternDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGraphPatternReference()
  {
    return graphPatternReferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGraphPatternReference_Referred()
  {
    return (EReference)graphPatternReferenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGraphPattern()
  {
    return graphPatternEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConfigSpecification()
  {
    return configSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getConfigSpecification_Entries()
  {
    return (EReference)configSpecificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConfigDeclaration()
  {
    return configDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getConfigDeclaration_Specification()
  {
    return (EReference)configDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConfigEntry()
  {
    return configEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDocumentationEntry()
  {
    return documentationEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDocumentationEntry_Level()
  {
    return (EAttribute)documentationEntryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRuntimeEntry()
  {
    return runtimeEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRuntimeEntry_MillisecLimit()
  {
    return (EAttribute)runtimeEntryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMemoryEntry()
  {
    return memoryEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMemoryEntry_MegabyteLimit()
  {
    return (EAttribute)memoryEntryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCustomEntry()
  {
    return customEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCustomEntry_Key()
  {
    return (EAttribute)customEntryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCustomEntry_Value()
  {
    return (EAttribute)customEntryEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConfigReference()
  {
    return configReferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getConfigReference_Config()
  {
    return (EReference)configReferenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConfig()
  {
    return configEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getScopeSpecification()
  {
    return scopeSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getScopeSpecification_Scopes()
  {
    return (EReference)scopeSpecificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTypeScope()
  {
    return typeScopeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTypeScope_SetsNew()
  {
    return (EAttribute)typeScopeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTypeScope_SetsSum()
  {
    return (EAttribute)typeScopeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTypeScope_Number()
  {
    return (EReference)typeScopeEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getClassTypeScope()
  {
    return classTypeScopeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getClassTypeScope_Type()
  {
    return (EReference)classTypeScopeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getObjectTypeScope()
  {
    return objectTypeScopeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getObjectTypeScope_Type()
  {
    return (EReference)objectTypeScopeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegerTypeScope()
  {
    return integerTypeScopeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegerTypeScope_Type()
  {
    return (EReference)integerTypeScopeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRealTypeScope()
  {
    return realTypeScopeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRealTypeScope_Type()
  {
    return (EReference)realTypeScopeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStringTypeScope()
  {
    return stringTypeScopeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStringTypeScope_Type()
  {
    return (EReference)stringTypeScopeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTypeReference()
  {
    return typeReferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getClassReference()
  {
    return classReferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getClassReference_Element()
  {
    return (EReference)classReferenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getObjectReference()
  {
    return objectReferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegerReference()
  {
    return integerReferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRealReference()
  {
    return realReferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStringReference()
  {
    return stringReferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNumberSpecification()
  {
    return numberSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExactNumber()
  {
    return exactNumberEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExactNumber_ExactNumber()
  {
    return (EAttribute)exactNumberEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExactNumber_ExactUnlimited()
  {
    return (EAttribute)exactNumberEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntervallNumber()
  {
    return intervallNumberEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIntervallNumber_Min()
  {
    return (EAttribute)intervallNumberEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIntervallNumber_MaxNumber()
  {
    return (EAttribute)intervallNumberEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIntervallNumber_MaxUnlimited()
  {
    return (EAttribute)intervallNumberEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntEnumberation()
  {
    return intEnumberationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIntEnumberation_Entry()
  {
    return (EAttribute)intEnumberationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRealEnumeration()
  {
    return realEnumerationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRealEnumeration_Entry()
  {
    return (EAttribute)realEnumerationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStringEnumeration()
  {
    return stringEnumerationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStringEnumeration_Entry()
  {
    return (EAttribute)stringEnumerationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getScopeDeclaration()
  {
    return scopeDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getScopeDeclaration_Specification()
  {
    return (EReference)scopeDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getScopeReference()
  {
    return scopeReferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getScopeReference_Referred()
  {
    return (EReference)scopeReferenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getScope()
  {
    return scopeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTask()
  {
    return taskEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGenerationTask()
  {
    return generationTaskEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenerationTask_Metamodel()
  {
    return (EReference)generationTaskEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenerationTask_PartialModel()
  {
    return (EReference)generationTaskEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenerationTask_Patterns()
  {
    return (EReference)generationTaskEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenerationTask_Scope()
  {
    return (EReference)generationTaskEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGenerationTask_NumberSpecified()
  {
    return (EAttribute)generationTaskEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGenerationTask_Number()
  {
    return (EAttribute)generationTaskEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGenerationTask_RunSpecified()
  {
    return (EAttribute)generationTaskEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGenerationTask_Runs()
  {
    return (EAttribute)generationTaskEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGenerationTask_Solver()
  {
    return (EAttribute)generationTaskEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenerationTask_Config()
  {
    return (EReference)generationTaskEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenerationTask_DebugFolder()
  {
    return (EReference)generationTaskEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenerationTask_TargetLogFile()
  {
    return (EReference)generationTaskEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenerationTask_TargetStatisticsFile()
  {
    return (EReference)generationTaskEClass.getEStructuralFeatures().get(12);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGenerationTask_TagetFolder()
  {
    return (EReference)generationTaskEClass.getEStructuralFeatures().get(13);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegerScope()
  {
    return integerScopeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRealScope()
  {
    return realScopeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStringScope()
  {
    return stringScopeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getDocumentLevelSpecification()
  {
    return documentLevelSpecificationEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getSolver()
  {
    return solverEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ApplicationConfigurationFactory getApplicationConfigurationFactory()
  {
    return (ApplicationConfigurationFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    configurationScriptEClass = createEClass(CONFIGURATION_SCRIPT);
    createEReference(configurationScriptEClass, CONFIGURATION_SCRIPT__IMPORTS);
    createEReference(configurationScriptEClass, CONFIGURATION_SCRIPT__COMMANDS);

    commandEClass = createEClass(COMMAND);

    importEClass = createEClass(IMPORT);

    ePackageImportEClass = createEClass(EPACKAGE_IMPORT);
    createEReference(ePackageImportEClass, EPACKAGE_IMPORT__IMPORTED_PACKAGE);

    viatraImportEClass = createEClass(VIATRA_IMPORT);
    createEReference(viatraImportEClass, VIATRA_IMPORT__IMPORTED_VIATRA);

    declarationEClass = createEClass(DECLARATION);
    createEAttribute(declarationEClass, DECLARATION__NAME);

    fileSpecificationEClass = createEClass(FILE_SPECIFICATION);
    createEAttribute(fileSpecificationEClass, FILE_SPECIFICATION__PATH);

    fileDeclarationEClass = createEClass(FILE_DECLARATION);
    createEReference(fileDeclarationEClass, FILE_DECLARATION__SPECIFICATION);

    fileReferenceEClass = createEClass(FILE_REFERENCE);
    createEReference(fileReferenceEClass, FILE_REFERENCE__REFERRED);

    fileEClass = createEClass(FILE);

    metamodelSpecificationEClass = createEClass(METAMODEL_SPECIFICATION);
    createEReference(metamodelSpecificationEClass, METAMODEL_SPECIFICATION__ENTRIES);

    metamodelEntryEClass = createEClass(METAMODEL_ENTRY);
    createEReference(metamodelEntryEClass, METAMODEL_ENTRY__PACKAGE);

    allPackageEntryEClass = createEClass(ALL_PACKAGE_ENTRY);
    createEReference(allPackageEntryEClass, ALL_PACKAGE_ENTRY__EXCLUSION);

    metamodelElementEClass = createEClass(METAMODEL_ELEMENT);
    createEReference(metamodelElementEClass, METAMODEL_ELEMENT__CLASSIFIER);
    createEReference(metamodelElementEClass, METAMODEL_ELEMENT__FEATURE);

    metamodelDeclarationEClass = createEClass(METAMODEL_DECLARATION);
    createEReference(metamodelDeclarationEClass, METAMODEL_DECLARATION__SPECIFICATION);

    metamodelReferenceEClass = createEClass(METAMODEL_REFERENCE);
    createEReference(metamodelReferenceEClass, METAMODEL_REFERENCE__REFERRED);

    metamodelEClass = createEClass(METAMODEL);

    partialModelSpecificationEClass = createEClass(PARTIAL_MODEL_SPECIFICATION);
    createEReference(partialModelSpecificationEClass, PARTIAL_MODEL_SPECIFICATION__ENTRY);

    partialModelEntryEClass = createEClass(PARTIAL_MODEL_ENTRY);
    createEReference(partialModelEntryEClass, PARTIAL_MODEL_ENTRY__PATH);

    modelEntryEClass = createEClass(MODEL_ENTRY);

    folderEntryEClass = createEClass(FOLDER_ENTRY);
    createEReference(folderEntryEClass, FOLDER_ENTRY__EXCLUSION);

    partialModelDeclarationEClass = createEClass(PARTIAL_MODEL_DECLARATION);
    createEReference(partialModelDeclarationEClass, PARTIAL_MODEL_DECLARATION__SPECIFICATION);

    partialModelReferenceEClass = createEClass(PARTIAL_MODEL_REFERENCE);
    createEReference(partialModelReferenceEClass, PARTIAL_MODEL_REFERENCE__REFERRED);

    partialModelEClass = createEClass(PARTIAL_MODEL);

    patternSpecificationEClass = createEClass(PATTERN_SPECIFICATION);
    createEReference(patternSpecificationEClass, PATTERN_SPECIFICATION__ENTRIES);

    patternEntryEClass = createEClass(PATTERN_ENTRY);
    createEReference(patternEntryEClass, PATTERN_ENTRY__PACKAGE);

    allPatternEntryEClass = createEClass(ALL_PATTERN_ENTRY);
    createEReference(allPatternEntryEClass, ALL_PATTERN_ENTRY__EXCLUSUION);

    patternElementEClass = createEClass(PATTERN_ELEMENT);
    createEReference(patternElementEClass, PATTERN_ELEMENT__PATTERN);

    graphPatternDeclarationEClass = createEClass(GRAPH_PATTERN_DECLARATION);
    createEReference(graphPatternDeclarationEClass, GRAPH_PATTERN_DECLARATION__SPECIFICATION);

    graphPatternReferenceEClass = createEClass(GRAPH_PATTERN_REFERENCE);
    createEReference(graphPatternReferenceEClass, GRAPH_PATTERN_REFERENCE__REFERRED);

    graphPatternEClass = createEClass(GRAPH_PATTERN);

    configSpecificationEClass = createEClass(CONFIG_SPECIFICATION);
    createEReference(configSpecificationEClass, CONFIG_SPECIFICATION__ENTRIES);

    configDeclarationEClass = createEClass(CONFIG_DECLARATION);
    createEReference(configDeclarationEClass, CONFIG_DECLARATION__SPECIFICATION);

    configEntryEClass = createEClass(CONFIG_ENTRY);

    documentationEntryEClass = createEClass(DOCUMENTATION_ENTRY);
    createEAttribute(documentationEntryEClass, DOCUMENTATION_ENTRY__LEVEL);

    runtimeEntryEClass = createEClass(RUNTIME_ENTRY);
    createEAttribute(runtimeEntryEClass, RUNTIME_ENTRY__MILLISEC_LIMIT);

    memoryEntryEClass = createEClass(MEMORY_ENTRY);
    createEAttribute(memoryEntryEClass, MEMORY_ENTRY__MEGABYTE_LIMIT);

    customEntryEClass = createEClass(CUSTOM_ENTRY);
    createEAttribute(customEntryEClass, CUSTOM_ENTRY__KEY);
    createEAttribute(customEntryEClass, CUSTOM_ENTRY__VALUE);

    configReferenceEClass = createEClass(CONFIG_REFERENCE);
    createEReference(configReferenceEClass, CONFIG_REFERENCE__CONFIG);

    configEClass = createEClass(CONFIG);

    scopeSpecificationEClass = createEClass(SCOPE_SPECIFICATION);
    createEReference(scopeSpecificationEClass, SCOPE_SPECIFICATION__SCOPES);

    typeScopeEClass = createEClass(TYPE_SCOPE);
    createEAttribute(typeScopeEClass, TYPE_SCOPE__SETS_NEW);
    createEAttribute(typeScopeEClass, TYPE_SCOPE__SETS_SUM);
    createEReference(typeScopeEClass, TYPE_SCOPE__NUMBER);

    classTypeScopeEClass = createEClass(CLASS_TYPE_SCOPE);
    createEReference(classTypeScopeEClass, CLASS_TYPE_SCOPE__TYPE);

    objectTypeScopeEClass = createEClass(OBJECT_TYPE_SCOPE);
    createEReference(objectTypeScopeEClass, OBJECT_TYPE_SCOPE__TYPE);

    integerTypeScopeEClass = createEClass(INTEGER_TYPE_SCOPE);
    createEReference(integerTypeScopeEClass, INTEGER_TYPE_SCOPE__TYPE);

    realTypeScopeEClass = createEClass(REAL_TYPE_SCOPE);
    createEReference(realTypeScopeEClass, REAL_TYPE_SCOPE__TYPE);

    stringTypeScopeEClass = createEClass(STRING_TYPE_SCOPE);
    createEReference(stringTypeScopeEClass, STRING_TYPE_SCOPE__TYPE);

    typeReferenceEClass = createEClass(TYPE_REFERENCE);

    classReferenceEClass = createEClass(CLASS_REFERENCE);
    createEReference(classReferenceEClass, CLASS_REFERENCE__ELEMENT);

    objectReferenceEClass = createEClass(OBJECT_REFERENCE);

    integerReferenceEClass = createEClass(INTEGER_REFERENCE);

    realReferenceEClass = createEClass(REAL_REFERENCE);

    stringReferenceEClass = createEClass(STRING_REFERENCE);

    numberSpecificationEClass = createEClass(NUMBER_SPECIFICATION);

    exactNumberEClass = createEClass(EXACT_NUMBER);
    createEAttribute(exactNumberEClass, EXACT_NUMBER__EXACT_NUMBER);
    createEAttribute(exactNumberEClass, EXACT_NUMBER__EXACT_UNLIMITED);

    intervallNumberEClass = createEClass(INTERVALL_NUMBER);
    createEAttribute(intervallNumberEClass, INTERVALL_NUMBER__MIN);
    createEAttribute(intervallNumberEClass, INTERVALL_NUMBER__MAX_NUMBER);
    createEAttribute(intervallNumberEClass, INTERVALL_NUMBER__MAX_UNLIMITED);

    intEnumberationEClass = createEClass(INT_ENUMBERATION);
    createEAttribute(intEnumberationEClass, INT_ENUMBERATION__ENTRY);

    realEnumerationEClass = createEClass(REAL_ENUMERATION);
    createEAttribute(realEnumerationEClass, REAL_ENUMERATION__ENTRY);

    stringEnumerationEClass = createEClass(STRING_ENUMERATION);
    createEAttribute(stringEnumerationEClass, STRING_ENUMERATION__ENTRY);

    scopeDeclarationEClass = createEClass(SCOPE_DECLARATION);
    createEReference(scopeDeclarationEClass, SCOPE_DECLARATION__SPECIFICATION);

    scopeReferenceEClass = createEClass(SCOPE_REFERENCE);
    createEReference(scopeReferenceEClass, SCOPE_REFERENCE__REFERRED);

    scopeEClass = createEClass(SCOPE);

    taskEClass = createEClass(TASK);

    generationTaskEClass = createEClass(GENERATION_TASK);
    createEReference(generationTaskEClass, GENERATION_TASK__METAMODEL);
    createEReference(generationTaskEClass, GENERATION_TASK__PARTIAL_MODEL);
    createEReference(generationTaskEClass, GENERATION_TASK__PATTERNS);
    createEReference(generationTaskEClass, GENERATION_TASK__SCOPE);
    createEAttribute(generationTaskEClass, GENERATION_TASK__NUMBER_SPECIFIED);
    createEAttribute(generationTaskEClass, GENERATION_TASK__NUMBER);
    createEAttribute(generationTaskEClass, GENERATION_TASK__RUN_SPECIFIED);
    createEAttribute(generationTaskEClass, GENERATION_TASK__RUNS);
    createEAttribute(generationTaskEClass, GENERATION_TASK__SOLVER);
    createEReference(generationTaskEClass, GENERATION_TASK__CONFIG);
    createEReference(generationTaskEClass, GENERATION_TASK__DEBUG_FOLDER);
    createEReference(generationTaskEClass, GENERATION_TASK__TARGET_LOG_FILE);
    createEReference(generationTaskEClass, GENERATION_TASK__TARGET_STATISTICS_FILE);
    createEReference(generationTaskEClass, GENERATION_TASK__TAGET_FOLDER);

    integerScopeEClass = createEClass(INTEGER_SCOPE);

    realScopeEClass = createEClass(REAL_SCOPE);

    stringScopeEClass = createEClass(STRING_SCOPE);

    // Create enums
    documentLevelSpecificationEEnum = createEEnum(DOCUMENT_LEVEL_SPECIFICATION);
    solverEEnum = createEEnum(SOLVER);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Obtain other dependent packages
    EcorePackage theEcorePackage = (EcorePackage)EPackage.Registry.INSTANCE.getEPackage(EcorePackage.eNS_URI);
    PatternLanguagePackage thePatternLanguagePackage = (PatternLanguagePackage)EPackage.Registry.INSTANCE.getEPackage(PatternLanguagePackage.eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    ePackageImportEClass.getESuperTypes().add(this.getImport());
    viatraImportEClass.getESuperTypes().add(this.getImport());
    declarationEClass.getESuperTypes().add(this.getCommand());
    fileSpecificationEClass.getESuperTypes().add(this.getFile());
    fileDeclarationEClass.getESuperTypes().add(this.getDeclaration());
    fileReferenceEClass.getESuperTypes().add(this.getFile());
    metamodelSpecificationEClass.getESuperTypes().add(this.getMetamodel());
    allPackageEntryEClass.getESuperTypes().add(this.getMetamodelEntry());
    metamodelElementEClass.getESuperTypes().add(this.getMetamodelEntry());
    metamodelDeclarationEClass.getESuperTypes().add(this.getDeclaration());
    metamodelReferenceEClass.getESuperTypes().add(this.getMetamodel());
    partialModelSpecificationEClass.getESuperTypes().add(this.getPartialModel());
    modelEntryEClass.getESuperTypes().add(this.getPartialModelEntry());
    folderEntryEClass.getESuperTypes().add(this.getPartialModelEntry());
    partialModelDeclarationEClass.getESuperTypes().add(this.getDeclaration());
    partialModelReferenceEClass.getESuperTypes().add(this.getPartialModel());
    patternSpecificationEClass.getESuperTypes().add(this.getGraphPattern());
    allPatternEntryEClass.getESuperTypes().add(this.getPatternEntry());
    patternElementEClass.getESuperTypes().add(this.getPatternEntry());
    graphPatternDeclarationEClass.getESuperTypes().add(this.getDeclaration());
    graphPatternReferenceEClass.getESuperTypes().add(this.getGraphPattern());
    configSpecificationEClass.getESuperTypes().add(this.getConfig());
    configDeclarationEClass.getESuperTypes().add(this.getDeclaration());
    documentationEntryEClass.getESuperTypes().add(this.getConfigEntry());
    runtimeEntryEClass.getESuperTypes().add(this.getConfigEntry());
    memoryEntryEClass.getESuperTypes().add(this.getConfigEntry());
    customEntryEClass.getESuperTypes().add(this.getConfigEntry());
    configReferenceEClass.getESuperTypes().add(this.getConfig());
    scopeSpecificationEClass.getESuperTypes().add(this.getScope());
    classTypeScopeEClass.getESuperTypes().add(this.getTypeScope());
    objectTypeScopeEClass.getESuperTypes().add(this.getTypeScope());
    integerTypeScopeEClass.getESuperTypes().add(this.getTypeScope());
    realTypeScopeEClass.getESuperTypes().add(this.getTypeScope());
    stringTypeScopeEClass.getESuperTypes().add(this.getTypeScope());
    classReferenceEClass.getESuperTypes().add(this.getTypeReference());
    objectReferenceEClass.getESuperTypes().add(this.getTypeReference());
    integerReferenceEClass.getESuperTypes().add(this.getTypeReference());
    realReferenceEClass.getESuperTypes().add(this.getTypeReference());
    stringReferenceEClass.getESuperTypes().add(this.getTypeReference());
    exactNumberEClass.getESuperTypes().add(this.getNumberSpecification());
    intervallNumberEClass.getESuperTypes().add(this.getNumberSpecification());
    intEnumberationEClass.getESuperTypes().add(this.getNumberSpecification());
    realEnumerationEClass.getESuperTypes().add(this.getNumberSpecification());
    stringEnumerationEClass.getESuperTypes().add(this.getNumberSpecification());
    scopeDeclarationEClass.getESuperTypes().add(this.getDeclaration());
    scopeReferenceEClass.getESuperTypes().add(this.getScope());
    taskEClass.getESuperTypes().add(this.getCommand());
    generationTaskEClass.getESuperTypes().add(this.getTask());
    integerScopeEClass.getESuperTypes().add(this.getIntegerReference());
    realScopeEClass.getESuperTypes().add(this.getRealReference());
    stringScopeEClass.getESuperTypes().add(this.getStringReference());

    // Initialize classes and features; add operations and parameters
    initEClass(configurationScriptEClass, ConfigurationScript.class, "ConfigurationScript", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getConfigurationScript_Imports(), this.getImport(), null, "imports", null, 0, -1, ConfigurationScript.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConfigurationScript_Commands(), this.getCommand(), null, "commands", null, 0, -1, ConfigurationScript.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(commandEClass, Command.class, "Command", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(importEClass, Import.class, "Import", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(ePackageImportEClass, EPackageImport.class, "EPackageImport", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEPackageImport_ImportedPackage(), theEcorePackage.getEPackage(), null, "importedPackage", null, 0, 1, EPackageImport.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(viatraImportEClass, ViatraImport.class, "ViatraImport", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getViatraImport_ImportedViatra(), thePatternLanguagePackage.getPatternModel(), null, "importedViatra", null, 0, 1, ViatraImport.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declarationEClass, Declaration.class, "Declaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDeclaration_Name(), theEcorePackage.getEString(), "name", null, 0, 1, Declaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fileSpecificationEClass, FileSpecification.class, "FileSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFileSpecification_Path(), theEcorePackage.getEString(), "path", null, 0, 1, FileSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fileDeclarationEClass, FileDeclaration.class, "FileDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFileDeclaration_Specification(), this.getFileSpecification(), null, "specification", null, 0, 1, FileDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fileReferenceEClass, FileReference.class, "FileReference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFileReference_Referred(), this.getFileDeclaration(), null, "referred", null, 0, 1, FileReference.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fileEClass, File.class, "File", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(metamodelSpecificationEClass, MetamodelSpecification.class, "MetamodelSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMetamodelSpecification_Entries(), this.getMetamodelEntry(), null, "entries", null, 0, -1, MetamodelSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(metamodelEntryEClass, MetamodelEntry.class, "MetamodelEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMetamodelEntry_Package(), theEcorePackage.getEPackage(), null, "package", null, 0, 1, MetamodelEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(allPackageEntryEClass, AllPackageEntry.class, "AllPackageEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAllPackageEntry_Exclusion(), this.getMetamodelElement(), null, "exclusion", null, 0, -1, AllPackageEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(metamodelElementEClass, MetamodelElement.class, "MetamodelElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMetamodelElement_Classifier(), theEcorePackage.getEClassifier(), null, "classifier", null, 0, 1, MetamodelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMetamodelElement_Feature(), theEcorePackage.getENamedElement(), null, "feature", null, 0, 1, MetamodelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(metamodelDeclarationEClass, MetamodelDeclaration.class, "MetamodelDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMetamodelDeclaration_Specification(), this.getMetamodelSpecification(), null, "specification", null, 0, 1, MetamodelDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(metamodelReferenceEClass, MetamodelReference.class, "MetamodelReference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMetamodelReference_Referred(), this.getMetamodelDeclaration(), null, "referred", null, 0, 1, MetamodelReference.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(metamodelEClass, Metamodel.class, "Metamodel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(partialModelSpecificationEClass, PartialModelSpecification.class, "PartialModelSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPartialModelSpecification_Entry(), this.getPartialModelEntry(), null, "entry", null, 0, -1, PartialModelSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(partialModelEntryEClass, PartialModelEntry.class, "PartialModelEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPartialModelEntry_Path(), this.getFile(), null, "path", null, 0, 1, PartialModelEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modelEntryEClass, ModelEntry.class, "ModelEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(folderEntryEClass, FolderEntry.class, "FolderEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFolderEntry_Exclusion(), this.getModelEntry(), null, "exclusion", null, 0, -1, FolderEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(partialModelDeclarationEClass, PartialModelDeclaration.class, "PartialModelDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPartialModelDeclaration_Specification(), this.getPartialModelSpecification(), null, "specification", null, 0, 1, PartialModelDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(partialModelReferenceEClass, PartialModelReference.class, "PartialModelReference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPartialModelReference_Referred(), this.getPartialModelDeclaration(), null, "referred", null, 0, 1, PartialModelReference.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(partialModelEClass, PartialModel.class, "PartialModel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(patternSpecificationEClass, PatternSpecification.class, "PatternSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPatternSpecification_Entries(), this.getPatternEntry(), null, "entries", null, 0, -1, PatternSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(patternEntryEClass, PatternEntry.class, "PatternEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPatternEntry_Package(), thePatternLanguagePackage.getPatternModel(), null, "package", null, 0, 1, PatternEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(allPatternEntryEClass, AllPatternEntry.class, "AllPatternEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAllPatternEntry_Exclusuion(), this.getPatternElement(), null, "exclusuion", null, 0, -1, AllPatternEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(patternElementEClass, PatternElement.class, "PatternElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPatternElement_Pattern(), thePatternLanguagePackage.getPattern(), null, "pattern", null, 0, 1, PatternElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(graphPatternDeclarationEClass, GraphPatternDeclaration.class, "GraphPatternDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getGraphPatternDeclaration_Specification(), this.getPatternSpecification(), null, "specification", null, 0, 1, GraphPatternDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(graphPatternReferenceEClass, GraphPatternReference.class, "GraphPatternReference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getGraphPatternReference_Referred(), this.getGraphPatternDeclaration(), null, "referred", null, 0, 1, GraphPatternReference.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(graphPatternEClass, GraphPattern.class, "GraphPattern", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(configSpecificationEClass, ConfigSpecification.class, "ConfigSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getConfigSpecification_Entries(), this.getConfigEntry(), null, "entries", null, 0, -1, ConfigSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(configDeclarationEClass, ConfigDeclaration.class, "ConfigDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getConfigDeclaration_Specification(), this.getConfigSpecification(), null, "specification", null, 0, 1, ConfigDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(configEntryEClass, ConfigEntry.class, "ConfigEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(documentationEntryEClass, DocumentationEntry.class, "DocumentationEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDocumentationEntry_Level(), this.getDocumentLevelSpecification(), "level", null, 0, 1, DocumentationEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(runtimeEntryEClass, RuntimeEntry.class, "RuntimeEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRuntimeEntry_MillisecLimit(), theEcorePackage.getEInt(), "millisecLimit", null, 0, 1, RuntimeEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(memoryEntryEClass, MemoryEntry.class, "MemoryEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMemoryEntry_MegabyteLimit(), theEcorePackage.getEInt(), "megabyteLimit", null, 0, 1, MemoryEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(customEntryEClass, CustomEntry.class, "CustomEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCustomEntry_Key(), theEcorePackage.getEString(), "key", null, 0, 1, CustomEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCustomEntry_Value(), theEcorePackage.getEString(), "value", null, 0, 1, CustomEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(configReferenceEClass, ConfigReference.class, "ConfigReference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getConfigReference_Config(), this.getConfigDeclaration(), null, "config", null, 0, 1, ConfigReference.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(configEClass, Config.class, "Config", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(scopeSpecificationEClass, ScopeSpecification.class, "ScopeSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getScopeSpecification_Scopes(), this.getTypeScope(), null, "scopes", null, 0, -1, ScopeSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(typeScopeEClass, TypeScope.class, "TypeScope", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTypeScope_SetsNew(), theEcorePackage.getEBoolean(), "setsNew", null, 0, 1, TypeScope.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTypeScope_SetsSum(), theEcorePackage.getEBoolean(), "setsSum", null, 0, 1, TypeScope.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTypeScope_Number(), this.getNumberSpecification(), null, "number", null, 0, 1, TypeScope.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(classTypeScopeEClass, ClassTypeScope.class, "ClassTypeScope", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getClassTypeScope_Type(), this.getClassReference(), null, "type", null, 0, 1, ClassTypeScope.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(objectTypeScopeEClass, ObjectTypeScope.class, "ObjectTypeScope", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getObjectTypeScope_Type(), this.getObjectReference(), null, "type", null, 0, 1, ObjectTypeScope.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(integerTypeScopeEClass, IntegerTypeScope.class, "IntegerTypeScope", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIntegerTypeScope_Type(), this.getIntegerReference(), null, "type", null, 0, 1, IntegerTypeScope.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(realTypeScopeEClass, RealTypeScope.class, "RealTypeScope", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRealTypeScope_Type(), this.getRealReference(), null, "type", null, 0, 1, RealTypeScope.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stringTypeScopeEClass, StringTypeScope.class, "StringTypeScope", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getStringTypeScope_Type(), this.getStringReference(), null, "type", null, 0, 1, StringTypeScope.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(typeReferenceEClass, TypeReference.class, "TypeReference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(classReferenceEClass, ClassReference.class, "ClassReference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getClassReference_Element(), this.getMetamodelElement(), null, "element", null, 0, 1, ClassReference.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(objectReferenceEClass, ObjectReference.class, "ObjectReference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(integerReferenceEClass, IntegerReference.class, "IntegerReference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(realReferenceEClass, RealReference.class, "RealReference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(stringReferenceEClass, StringReference.class, "StringReference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(numberSpecificationEClass, NumberSpecification.class, "NumberSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(exactNumberEClass, ExactNumber.class, "ExactNumber", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getExactNumber_ExactNumber(), theEcorePackage.getEInt(), "exactNumber", null, 0, 1, ExactNumber.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getExactNumber_ExactUnlimited(), theEcorePackage.getEBoolean(), "exactUnlimited", null, 0, 1, ExactNumber.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(intervallNumberEClass, IntervallNumber.class, "IntervallNumber", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIntervallNumber_Min(), theEcorePackage.getEInt(), "min", null, 0, 1, IntervallNumber.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getIntervallNumber_MaxNumber(), theEcorePackage.getEInt(), "maxNumber", null, 0, 1, IntervallNumber.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getIntervallNumber_MaxUnlimited(), theEcorePackage.getEBoolean(), "maxUnlimited", null, 0, 1, IntervallNumber.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(intEnumberationEClass, IntEnumberation.class, "IntEnumberation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIntEnumberation_Entry(), theEcorePackage.getEInt(), "entry", null, 0, -1, IntEnumberation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(realEnumerationEClass, RealEnumeration.class, "RealEnumeration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRealEnumeration_Entry(), theEcorePackage.getEBigDecimal(), "entry", null, 0, -1, RealEnumeration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stringEnumerationEClass, StringEnumeration.class, "StringEnumeration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStringEnumeration_Entry(), theEcorePackage.getEString(), "entry", null, 0, -1, StringEnumeration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(scopeDeclarationEClass, ScopeDeclaration.class, "ScopeDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getScopeDeclaration_Specification(), this.getScopeSpecification(), null, "specification", null, 0, 1, ScopeDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(scopeReferenceEClass, ScopeReference.class, "ScopeReference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getScopeReference_Referred(), this.getScopeDeclaration(), null, "referred", null, 0, 1, ScopeReference.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(scopeEClass, Scope.class, "Scope", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(taskEClass, Task.class, "Task", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(generationTaskEClass, GenerationTask.class, "GenerationTask", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getGenerationTask_Metamodel(), this.getMetamodel(), null, "metamodel", null, 0, 1, GenerationTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGenerationTask_PartialModel(), this.getPartialModel(), null, "partialModel", null, 0, 1, GenerationTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGenerationTask_Patterns(), this.getGraphPattern(), null, "patterns", null, 0, 1, GenerationTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGenerationTask_Scope(), this.getScope(), null, "scope", null, 0, 1, GenerationTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGenerationTask_NumberSpecified(), theEcorePackage.getEBoolean(), "numberSpecified", null, 0, 1, GenerationTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGenerationTask_Number(), theEcorePackage.getEInt(), "number", null, 0, 1, GenerationTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGenerationTask_RunSpecified(), theEcorePackage.getEBoolean(), "runSpecified", null, 0, 1, GenerationTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGenerationTask_Runs(), theEcorePackage.getEInt(), "runs", null, 0, 1, GenerationTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGenerationTask_Solver(), this.getSolver(), "solver", null, 0, 1, GenerationTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGenerationTask_Config(), this.getConfig(), null, "config", null, 0, 1, GenerationTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGenerationTask_DebugFolder(), this.getFile(), null, "debugFolder", null, 0, 1, GenerationTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGenerationTask_TargetLogFile(), this.getFile(), null, "targetLogFile", null, 0, 1, GenerationTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGenerationTask_TargetStatisticsFile(), this.getFile(), null, "targetStatisticsFile", null, 0, 1, GenerationTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGenerationTask_TagetFolder(), this.getFile(), null, "tagetFolder", null, 0, 1, GenerationTask.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(integerScopeEClass, IntegerScope.class, "IntegerScope", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(realScopeEClass, RealScope.class, "RealScope", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(stringScopeEClass, StringScope.class, "StringScope", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    // Initialize enums and add enum literals
    initEEnum(documentLevelSpecificationEEnum, DocumentLevelSpecification.class, "DocumentLevelSpecification");
    addEEnumLiteral(documentLevelSpecificationEEnum, DocumentLevelSpecification.NONE);
    addEEnumLiteral(documentLevelSpecificationEEnum, DocumentLevelSpecification.NORMAL);
    addEEnumLiteral(documentLevelSpecificationEEnum, DocumentLevelSpecification.FULL);

    initEEnum(solverEEnum, Solver.class, "Solver");
    addEEnumLiteral(solverEEnum, Solver.SMT_SOLVER);
    addEEnumLiteral(solverEEnum, Solver.ALLOY_SOLVER);
    addEEnumLiteral(solverEEnum, Solver.VIATRA_SOLVER);
    addEEnumLiteral(solverEEnum, Solver.TPTP_SOLVER);

    // Create resource
    createResource(eNS_URI);
  }

} //ApplicationConfigurationPackageImpl
