/**
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.inf.dslreasoner.application.applicationConfiguration;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Optimization Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.OptimizationEntry#getDirection <em>Direction</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ApplicationConfigurationPackage#getOptimizationEntry()
 * @model
 * @generated
 */
public interface OptimizationEntry extends ObjectiveEntry
{
  /**
   * Returns the value of the '<em><b>Direction</b></em>' attribute.
   * The literals are from the enumeration {@link hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.OptimizationDirection}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' attribute.
   * @see hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.OptimizationDirection
   * @see #setDirection(OptimizationDirection)
   * @see hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.ApplicationConfigurationPackage#getOptimizationEntry_Direction()
   * @model
   * @generated
   */
  OptimizationDirection getDirection();

  /**
   * Sets the value of the '{@link hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.OptimizationEntry#getDirection <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' attribute.
   * @see hu.bme.mit.inf.dslreasoner.application.applicationConfiguration.OptimizationDirection
   * @see #getDirection()
   * @generated
   */
  void setDirection(OptimizationDirection value);

} // OptimizationEntry
