<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Taxation" nsURI="http:///TaxCard.ecore" nsPrefix="TaxCard">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="Grantor">
    <eLiterals name="WWW" literal="WWW"/>
    <eLiterals name="Employer" value="1" literal="Employer"/>
    <eLiterals name="MMM" value="2" literal="MMM"/>
    <eLiterals name="UUU" value="3" literal="UUU"/>
    <eLiterals name="YYY" value="4" literal="YYY"/>
    <eLiterals name="OOO" value="5" literal="OOO"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constants" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MAXIMUM_CE_RATE_FOR_CHILD_NOT_BEING_PART_OF_HOUSEHOLD"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="3480.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MAXIMUM_CE_RATE_FOR_HOUSE_CARE_AND_CHILD_PART_OF_THE_HOUSEHOLD_CARE"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="3600.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MINIMUM_SALARY" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="1500.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FLAT_RATE_FOR_EXTRA_PROFESSIONAL_DEDUCTION"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="4500.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MAXIMUM_DEDUCTIBLE_PERCENTAGE_FOR_DONATIONS"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="20.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MINIMUM_DEDUCTIBLE_AMOUNT_FOR_DONATIONS"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="120.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MAXIMUM_DEDUCTIBLE_AMOUNT_FOR_ADDITIONAL_PENSION_AND_INSURANC"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MAXIMUM_DEDUCTIBLE_AMOUNT_FOR_ALIMONY_EXPENSE"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="24000.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MAXIMAL_DISTANCE_FOR_TRAVEL_EXPENSE_DEDUCTION"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="99.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MAXIMAL_FLAT_DISTANCE_FOR_TRAVEL_EXPENSE_DEDUCTION"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="30.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MINIMAL_DISTANCE_FOR_TRAVEL_EXPENSE_DEDUCTION"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="4.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FLAT_RATE_CIM_DAILY" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="2.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FLAT_RATE_CIM_MONTHLY"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="62.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FLAT_RATE_CIM_YEARLY" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="750.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FLAT_RATE_CIP_DAILY" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FLAT_RATE_CIP_MONTHLY"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="25.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FLAT_RATE_CIP_YEARLY" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="30.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FLAT_RATE_CIS_DAILY" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FLAT_RATE_CIS_MONTHLY"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="25.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FLAT_RATE_CIS_YEARLY" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="300.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FLAT_RATE_FOR_TRAVEL_EXPENSE_PER_UNIT"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="99.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MAXIMUM_DEDUCTIBLE_AMOUNT_FOR_DS"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FLAT_RATE_FOR_MISCELLANEOUS_EXPENSE"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DISABILITY_FLAT_RATE_FOR_MISCELLANEOUS_EXPENSE"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MAXIMUM_DEDUCTIBLE_AMOUNT_FOR_ADDITIONAL_PENSION_AND_INSURANCE"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Disability_Types">
    <eLiterals name="beug"/>
    <eLiterals name="NONE" value="1"/>
    <eLiterals name="A" value="2" literal="A"/>
    <eLiterals name="B" value="3" literal="B"/>
    <eLiterals name="C" value="4" literal="C"/>
    <eLiterals name="D" value="5" literal="D"/>
    <eLiterals name="E" value="6" literal="E"/>
    <eLiterals name="OTHER" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Country">
    <eLiterals name="ZZ" literal="ZZ"/>
    <eLiterals name="FF" value="1" literal="FF"/>
    <eLiterals name="BB" value="2" literal="BB"/>
    <eLiterals name="DD" value="3" literal="DD"/>
    <eLiterals name="NN" value="4" literal="NN"/>
    <eLiterals name="OTHER" value="5" literal="OTHER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Tax_Office">
    <eLiterals name="RTS_2" literal="RTS_2"/>
    <eLiterals name="RTS_3" value="1" literal="RTS_3"/>
    <eLiterals name="RTS_4" value="2" literal="RTS_4"/>
    <eLiterals name="RTS_5" value="3" literal="RTS_5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Tax_Class_Category">
    <eLiterals name="One" literal="One"/>
    <eLiterals name="One_A" value="1" literal="One_A"/>
    <eLiterals name="Two" value="2" literal="Two"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Job_Activity">
    <eLiterals name="Salary" literal="Salary"/>
    <eLiterals name="Pension" value="1" literal="Pension"/>
    <eLiterals name="Annuity" value="2" literal="Annuity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Town">
    <eLiterals name="LL" literal="LL"/>
    <eLiterals name="BB" value="1" literal="BB"/>
    <eLiterals name="SS" value="2" literal="SS"/>
    <eLiterals name="TT" value="3" literal="TT"/>
    <eLiterals name="Other" value="4" literal="Other"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CE_Type">
    <eLiterals name="INALIDITY_AND_INFIRMITY" literal="INALIDITY_AND_INFIRMITY"/>
    <eLiterals name="DEPENDENCE_AND_CARE_EXCLUDING_CHLIDREN_NOT_PART_OF_HOUSEHOLD"
        value="1" literal="DEPENDENCE_AND_CARE_EXCLUDING_CHLIDREN_NOT_PART_OF_HOUSEHOLD"/>
    <eLiterals name="CARE_FOR_CHILDREN_NOT_BEING_PART_OF_HOUSEHOLD" value="2" literal="CARE_FOR_CHILDREN_NOT_BEING_PART_OF_HOUSEHOLD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Expense_Purpose">
    <eLiterals name="HOUSE_CARE" literal="HOUSE_CARE"/>
    <eLiterals name="CHILD_CARE" value="1" literal="CHILD_CARE"/>
    <eLiterals name="DEPENDENCE_CARE" value="2" literal="DEPENDENCE_CARE"/>
    <eLiterals name="OTHER" value="3" literal="OTHER"/>
    <eLiterals name="ALIMONY" value="4"/>
    <eLiterals name="RECURRENT_DEPT" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Dependent_Type">
    <eLiterals name="CHILD" literal="CHILD"/>
    <eLiterals name="SPOUSE" value="1" literal="SPOUSE"/>
    <eLiterals name="RELATIVE" value="2" literal="RELATIVE"/>
    <eLiterals name="OTHER_FAMILY_MEMBER" value="3" literal="OTHER_FAMILY_MEMBER"/>
    <eLiterals name="NOT_OWN_CHILD" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Income_Tax">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taxPayer" lowerBound="1"
        eType="#//Tax_Payer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tax_amount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tax_year" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id6" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tax_Payer" abstract="true" eSuperTypes="#//Physical_Person #//Tax_Case">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EReference" name="expenses" ordered="false" upperBound="-1"
          eType="#//Expense" containment="true">
        <eAnnotations source="redefines" references="#//Physical_Person/expenses"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependents" ordered="false"
        upperBound="6" eType="#//Dependent" containment="true" eOpposite="#//Dependent/responsible_person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from_agent" lowerBound="1"
        eType="#//FromAgent" containment="true" eOpposite="#//FromAgent/taxPayer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomes" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Income" containment="true" eOpposite="#//Income/taxPayer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from_law" lowerBound="1"
        eType="#//FromLaw" containment="true" eOpposite="#//FromLaw/taxPayer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Physical_Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SSNo" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addresses" ordered="false"
        upperBound="-1" eType="#//Address" eOpposite="#//Address/taxPayer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birth_year" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disability_percentage"
        ordered="false" unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disability_type" ordered="false"
        unique="false" lowerBound="1" eType="#//Disability_Types"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birth_month" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birth_day" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expenses" ordered="false"
        upperBound="-1" eType="#//Expense" eOpposite="#//Expense/beneficiary"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_widower" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Address">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" lowerBound="1"
        eType="#//Country" defaultValueLiteral="ZZ"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zipCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id2" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taxPayer" ordered="false"
        upperBound="-1" eType="#//Physical_Person" eOpposite="#//Physical_Person/addresses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expense">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="declared_amount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expense_purpose" lowerBound="1"
        eType="#//Expense_Purpose" defaultValueLiteral="OTHER"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependent" eType="#//Dependent"
        eOpposite="#//Dependent/expense"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from_agent" ordered="false"
        eType="#//FromAgent" eOpposite="#//FromAgent/expense"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="income" lowerBound="1"
        eType="#//Income" eOpposite="#//Income/expenses"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id4" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beneficiary" ordered="false"
        eType="#//Physical_Person" eOpposite="#//Physical_Person/expenses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependent" eSuperTypes="#//Physical_Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dependent_type" lowerBound="1"
        eType="#//Dependent_Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsible_person" eType="#//Tax_Payer"
        eOpposite="#//Tax_Payer/dependents"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="continued_studies" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allowances" ordered="false"
        eType="#//External_Allowance" containment="true" eOpposite="#//External_Allowance/person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="household" ordered="false"
        eType="#//Household" eOpposite="#//Household/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from_agent" ordered="false"
        eType="#//FromAgent" eOpposite="#//FromAgent/dependent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expense" ordered="false"
        upperBound="-1" eType="#//Expense" eOpposite="#//Expense/dependent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="External_Allowance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grantor" lowerBound="1"
        eType="#//Grantor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="starting_year" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ending_year" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reciver" ordered="false"
        lowerBound="1" eType="#//Physical_Person"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id5" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" ordered="false"
        lowerBound="1" eType="#//Dependent" eOpposite="#//Dependent/allowances"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Household" eSuperTypes="#//Tax_Case">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parents" ordered="false"
        lowerBound="1" eType="#//Legal_Union_Record" containment="true" eOpposite="#//Legal_Union_Record/household"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id1" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" ordered="false"
        upperBound="-1" eType="#//Dependent" containment="true" eOpposite="#//Dependent/household"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Legal_Union_Record" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start_year" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end_year" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="separation_cause" ordered="false"
        lowerBound="1" eType="#//Separation_Causes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="individual_A" ordered="false"
        lowerBound="1" eType="#//Physical_Person" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="legal_union_A"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="individual_B" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Physical_Person" containment="true">
      <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
        <details key="body" value="legal_union_B"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Tax_Property" containment="true"
        eOpposite="#//Tax_Property/union_record"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mutual_agreement" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id9" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="household" ordered="false"
        lowerBound="1" eType="#//Household" eOpposite="#//Household/parents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Separation_Causes">
    <eLiterals name="NONE"/>
    <eLiterals name="DIVORCE" value="1"/>
    <eLiterals name="SEPARATION_DE_FAIT" value="2"/>
    <eLiterals name="SEPARATION_BY_COURT" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tax_Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="starting_year" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id10" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="union_record" ordered="false"
        lowerBound="1" eType="#//Legal_Union_Record" eOpposite="#//Legal_Union_Record/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tax_Case" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FromAgent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taxPayer" lowerBound="1"
        eType="#//Tax_Payer" eOpposite="#//Tax_Payer/from_agent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_dependent_eligible_for_CE_Not_In_Houshold_Children_Care"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expense" ordered="false"
        eType="#//Expense" eOpposite="#//Expense/from_agent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_eligible_debt" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependent" ordered="false"
        eType="#//Dependent" eOpposite="#//Dependent/from_agent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Income" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="income_amount" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="let non_null_amounts:OrderedSet(Income_Detail)=self.details->select(det:Income_Detail|det.amount>0)->asOrderedSet() in&#xA;non_null_amounts->collect(amount)->min()"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="income_type" lowerBound="1"
        eType="#//Income_Type" containment="true" eOpposite="#//Income_Type/income"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tax_card" eType="#//Tax_Card"
        containment="true" eOpposite="#//Tax_Card/income"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tax_liability" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taxPayer" ordered="false"
        lowerBound="1" eType="#//Tax_Payer" eOpposite="#//Tax_Payer/incomes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" lowerBound="12"
        upperBound="12" eType="#//Income_Detail" containment="true" eOpposite="#//Income_Detail/income"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="num" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expenses" ordered="false"
        upperBound="-1" eType="#//Expense" containment="true" eOpposite="#//Expense/income"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Income_Type" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id8" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="income" lowerBound="1"
        eType="#//Income" eOpposite="#//Income/income_type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tax_Card">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="card_identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tax_office" lowerBound="1"
        eType="#//Tax_Office"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage_of_witholding"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tax_payers_name_surname"
        ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tax_payers_partner_name_surname"
        ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tax_payers_address" eType="#//Address"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobs_Employer_SSNo" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobs_employers_name" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobs_activity_type" lowerBound="1"
        eType="#//Job_Activity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobs_place_of_work" lowerBound="1"
        eType="#//Town"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_FD_daily" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_FD_monthly" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_AC_daily" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_AC_monthly" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_AC_yearly" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_CE_daily" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_CE_monthly" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_CE_yearly" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_DS_daily" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_DS_monthly" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_FO_daily" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_FO_monthly" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_FO_yearly" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credit_CIS_daily" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credit_CIS_monthly" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credit_CIM_daily" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="income_Tax_Credit" ordered="false"
        upperBound="-1" eType="#//Income_Tax_Credit" eOpposite="#//Income_Tax_Credit/taxation_Frame"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//Tax_Card"
        eOpposite="#//Tax_Card/current_tax_card"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="current_tax_card" eType="#//Tax_Card"
        eOpposite="#//Tax_Card/previous"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credit_CIM_yearly" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_DS_Alimony_yearly"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deduction_DS_Debt_yearly"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="income" lowerBound="1"
        eType="#//Income" eOpposite="#//Income/tax_card"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Income_Tax_Credit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grantedBy" lowerBound="1"
        eType="#//Grantor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taxPayer" eType="#//Tax_Payer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tax_year" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yearly" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="300.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monthly" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="25.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daily" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id7" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taxation_Frame" eType="#//Tax_Card"
        eOpposite="#//Tax_Card/income_Tax_Credit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Income_Detail">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_worked" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="worked_days" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_contributing_CNS" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id5" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="income" lowerBound="1"
        eType="#//Income" eOpposite="#//Income/details"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FromLaw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taxPayer" lowerBound="1"
        eType="#//Tax_Payer" eOpposite="#//Tax_Payer/from_law"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fiscal_Address" eSuperTypes="#//Address"/>
  <eClassifiers xsi:type="ecore:EClass" name="Habitual_Address" eSuperTypes="#//Address"/>
  <eClassifiers xsi:type="ecore:EClass" name="Marriage_Record" eSuperTypes="#//Legal_Union_Record"/>
  <eClassifiers xsi:type="ecore:EClass" name="Non_Resident_Tax_Payer" eSuperTypes="#//Tax_Payer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_assimilated_to_resident"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Partnership_Record" eSuperTypes="#//Legal_Union_Record"/>
  <eClassifiers xsi:type="ecore:EClass" name="Resident_Tax_Payer" eSuperTypes="#//Tax_Payer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Trade_and_Business_Income" eSuperTypes="#//Income_Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Agriculture_and_Forestry_Income" eSuperTypes="#//Income_Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pensions_and_Annuities_Income" eSuperTypes="#//Income_Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="occasional_payement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capital_and_Investments_Income" eSuperTypes="#//Income_Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Employment_Income" eSuperTypes="#//Income_Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rentals_and_Leases_Income" eSuperTypes="#//Income_Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_periodic" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Foreign_Income" eSuperTypes="#//Income"/>
  <eClassifiers xsi:type="ecore:EClass" name="Local_Income" eSuperTypes="#//Income"/>
  <eClassifiers xsi:type="ecore:EClass" name="CIM" eSuperTypes="#//Income_Tax_Credit"/>
  <eClassifiers xsi:type="ecore:EClass" name="CIP" eSuperTypes="#//Income_Tax_Credit"/>
  <eClassifiers xsi:type="ecore:EClass" name="CIS" eSuperTypes="#//Income_Tax_Credit"/>
  <eClassifiers xsi:type="ecore:EClass" name="FD" eSuperTypes="#//Professional_Expenses_Deduction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance_declared_in_january"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Professional_Expenses_Deduction"/>
  <eClassifiers xsi:type="ecore:EClass" name="FO" eSuperTypes="#//Professional_Expenses_Deduction"/>
  <eClassifiers xsi:type="ecore:EClass" name="DS_for_Permanent_Expense" eSuperTypes="#//DS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="permanent_expense_category"
        lowerBound="1" eType="#//Category_of_Permanent_Expense"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum_deductible_amount"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id3" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Category_of_Permanent_Expense">
    <eLiterals name="MISCELLANEOUS_DEBT" literal="MISCELLANEOUS_DEBT"/>
    <eLiterals name="ALIMONY" value="1" literal="ALIMONY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DS_for_Interest_Expense" eSuperTypes="#//DS"/>
  <eClassifiers xsi:type="ecore:EClass" name="DS_for_Health_and_Pension_Insurance"
      eSuperTypes="#//DS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insurance_category" lowerBound="1"
        eType="#//Category_of_Health_and_Pension_Insurances"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Category_of_Health_and_Pension_Insurances">
    <eLiterals name="MANDATORY_HEALTH_AND_PENSION_INSURANCE" literal="MANDATORY_HEALTH_AND_PENSION_INSURANCE"/>
    <eLiterals name="ADDITIONAL_EMPLOYERS_PENSION_INSURANCE" value="1" literal="ADDITIONAL_EMPLOYERS_PENSION_INSURANCE"/>
    <eLiterals name="CONTINUED_HEALTH_AND_PENSION_INSURANCE" value="2" literal="CONTINUED_HEALTH_AND_PENSION_INSURANCE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DS_for_Private_Insurance_and_Plan" eSuperTypes="#//DS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="private_insurance_and_plan_category"
        lowerBound="1" eType="#//Category_of_Private_Insurance_and_Plan"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Category_of_Private_Insurance_and_Plan">
    <eLiterals name="PRIVATE_INSURANCE" literal="PRIVATE_INSURANCE"/>
    <eLiterals name="PRIVATE_LIFE_INSURANCE" value="1" literal="PRIVATE_LIFE_INSURANCE"/>
    <eLiterals name="COMPANY_MEMBERS_PRIVATE_INSURANCE" value="2" literal="COMPANY_MEMBERS_PRIVATE_INSURANCE"/>
    <eLiterals name="HOUSING_SAVING_PLAN" value="3" literal="HOUSING_SAVING_PLAN"/>
    <eLiterals name="OLD_AGE_PENSION_PLAN" value="4" literal="OLD_AGE_PENSION_PLAN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DS_for_Loss_Carryforward" eSuperTypes="#//DS"/>
  <eClassifiers xsi:type="ecore:EClass" name="DS_for_Donation" eSuperTypes="#//DS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Permanent_Expense" eSuperTypes="#//Special_Expense_DS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" lowerBound="1"
        eType="#//Category_of_Permanent_Expense"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Special_Expense_DS" eSuperTypes="#//Expense"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interest_Expense" eSuperTypes="#//Special_Expense_DS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Private_Insurance_and_Plan" eSuperTypes="#//Special_Expense_DS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" lowerBound="1"
        eType="#//Category_of_Private_Insurance_and_Plan"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration_of_contract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Health_and_Pension_Insurance" eSuperTypes="#//Special_Expense_DS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" lowerBound="1"
        eType="#//Category_of_Health_and_Pension_Insurances"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_related_to_additional_salary"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Donation" eSuperTypes="#//Special_Expense_DS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beneficiary1" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is_donation_reported" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loss_Carryforward" eSuperTypes="#//Special_Expense_DS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Spousal_Expense_AC" eSuperTypes="#//Expense"/>
  <eClassifiers xsi:type="ecore:EClass" name="Extraordinary_Expense_CE" eSuperTypes="#//Expense">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thresholded_deduction_percentage"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ce_type" lowerBound="1"
        eType="#//CE_Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Travel_Expense_FD" eSuperTypes="#//Professional_Expense"/>
  <eClassifiers xsi:type="ecore:EClass" name="Professional_Expense" eSuperTypes="#//Expense"/>
  <eClassifiers xsi:type="ecore:EClass" name="Miscellaneous_Expense_FO" eSuperTypes="#//Professional_Expense"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Legal_Union_Types">
    <eLiterals name="MARIAGE"/>
    <eLiterals name="PARTNERSHIP" value="1"/>
    <eLiterals name="OTHER" value="2"/>
  </eClassifiers>
</ecore:EPackage>
