<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="crossingScenario" nsURI="http://www.example.com/crossingScenario"
    nsPrefix="crossingScenario">
  <eClassifiers xsi:type="ecore:EClass" name="CrossingScenario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ySize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
        eType="#//Actor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lanes" upperBound="-1"
        eType="#//Lane" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="horizontal_head" lowerBound="1"
        eType="#//Lane_Horizontal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertical_head" lowerBound="1"
        eType="#//Lane_Vertical"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lane" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="#//Size"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceCoord" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prevLane" eType="#//Lane"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
        eType="#//Actor" eOpposite="#//Actor/placedOn"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numWidth" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Size">
    <eLiterals name="S_Small"/>
    <eLiterals name="S_Med" value="1"/>
    <eLiterals name="S_Large" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xPos" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yPos" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xSpeed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//Relation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="placedOn" lowerBound="1"
        eType="#//Lane" eOpposite="#//Lane/actors"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ySpeed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Actor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpatialRelation" abstract="true" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="TemporalRelation" abstract="true" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="VisionBlocked" eSuperTypes="#//SpatialRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockedBy" lowerBound="1"
        eType="#//Actor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SeparationDistance" eSuperTypes="#//SpatialRelation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" lowerBound="1"
        eType="#//Distance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollisionExists" eSuperTypes="#//TemporalRelation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collisionTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollisionDoesNotExist" eSuperTypes="#//TemporalRelation"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Distance">
    <eLiterals name="D_Near"/>
    <eLiterals name="D_Med" value="1"/>
    <eLiterals name="D_Far" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pedestrian" eSuperTypes="#//Actor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle" eSuperTypes="#//Actor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lane_Horizontal" eSuperTypes="#//Lane"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lane_Vertical" eSuperTypes="#//Lane"/>
</ecore:EPackage>
