/**
 * generated by Xtext 2.18.0.M3
 */
package org.eclipse.viatra.solver.language.solverLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean False</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.viatra.solver.language.solverLanguage.SolverLanguagePackage#getBooleanFalse()
 * @model
 * @generated
 */
public interface BooleanFalse extends BooleanValue
{
} // BooleanFalse
