<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cft" nsURI="http://www.bme.hu/mit/inf/dslreasoner/faulttree/model/cft"
    nsPrefix="cft">
  <eClassifiers xsi:type="ecore:EClass" name="ComponentDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputEvents" upperBound="-1"
        eType="#//InputEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventDefinitions" upperBound="-1"
        eType="#//EventDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputEvents" upperBound="-1"
        eType="#//EventDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventDefinition" abstract="true" eSuperTypes="#//EventDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="GateDefinition" abstract="true" eSuperTypes="#//EventDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputEvents" upperBound="-1"
        eType="#//EventDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicEventDefinition" eSuperTypes="#//EventDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="distribution" lowerBound="1"
        eType="ecore:EClass ft.ecore#//Distribution" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputEvent" eSuperTypes="#//EventDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventDeclaration" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndGateDefinition" eSuperTypes="#//GateDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrGateDefinition" eSuperTypes="#//GateDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="KOfMGateDefinition" eSuperTypes="#//GateDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="k" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentFaultTree">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topEvent" lowerBound="1"
        eType="#//Output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//ModalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Input" containment="true" eOpposite="#//Input/component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Output" containment="true" eOpposite="#//Output/component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentDefinition" lowerBound="1"
        eType="#//ComponentDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleAllowed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputEvent" lowerBound="1"
        eType="#//InputEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//Component" eOpposite="#//Component/inputs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnections" upperBound="-1"
        eType="#//Connection" containment="true" eOpposite="#//Connection/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventDeclaration" lowerBound="1"
        eType="#//EventDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnections" upperBound="-1"
        eType="#//Connection" eOpposite="#//Connection/output"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//Component" eOpposite="#//Component/outputs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" eSuperTypes="#//ModalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" eType="#//Input"
        eOpposite="#//Input/incomingConnections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        eType="#//Output" eOpposite="#//Output/outgoingConnections"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Modality">
    <eLiterals name="MAY"/>
    <eLiterals name="CURRENT" value="1"/>
    <eLiterals name="MUST" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModalElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exists" eType="#//Modality"
        defaultValueLiteral="MUST"/>
  </eClassifiers>
</ecore:EPackage>
