<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ft" nsURI="http://www.bme.hu/mit/inf/dslreasoner/faulttree/model/ft"
    nsPrefix="ft">
  <eClassifiers xsi:type="ecore:EClass" name="FaultTree" eSuperTypes="#//ReliabilityModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//RandomEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topEvent" lowerBound="1"
        eType="#//RandomEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomEvent" abstract="true" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicEvent" eSuperTypes="#//RandomEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="distribution" lowerBound="1"
        eType="#//Distribution" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gate" abstract="true" eSuperTypes="#//RandomEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputEvents" lowerBound="2"
        upperBound="-1" eType="#//RandomEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Distribution" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantDistribution" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="p" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExponentialDistribution" eSuperTypes="#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lambda" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndGate" eSuperTypes="#//Gate"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrGate" eSuperTypes="#//Gate"/>
  <eClassifiers xsi:type="ecore:EClass" name="KOfMGate" eSuperTypes="#//Gate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="k" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReliabilityModel" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantModel" eSuperTypes="#//ReliabilityModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
