<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="solverLanguage" nsURI="http://www.eclipse.org/viatra/solver/language/SolverLanguage"
    nsPrefix="solverLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="PathComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbol" eType="#//Symbol"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inverse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitiveClosure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reflexiveTransitiveClosure"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Symbol" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functor" eType="#//Reference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentList" eType="#//ArgumentList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//PathComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="existsVariables" upperBound="-1"
        eType="#//Variable" transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Argument" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArgumentList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Argument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionArgument" eSuperTypes="#//Argument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StarArgument" eSuperTypes="#//Argument"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypedArgument" abstract="true" eSuperTypes="#//Argument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeReference" eType="#//TypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiaryExpession" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Symbol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeReference" eType="#//TypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//UnaryOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//BinaryOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Disjunction" eSuperTypes="#//MultiaryExpession"/>
  <eClassifiers xsi:type="ecore:EClass" name="Conjunction" eSuperTypes="#//MultiaryExpession"/>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryOperator">
    <eLiterals name="NOT"/>
    <eLiterals name="PLUS" value="1"/>
    <eLiterals name="MINUS" value="2"/>
    <eLiterals name="MAYBE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryOperator">
    <eLiterals name="PLUS"/>
    <eLiterals name="MINUS" value="1"/>
    <eLiterals name="MULTIPLY" value="2"/>
    <eLiterals name="DIVIDE" value="3"/>
    <eLiterals name="POW" value="4"/>
    <eLiterals name="IN" value="5"/>
    <eLiterals name="EQUALS" value="6"/>
    <eLiterals name="NOT_EQUALS" value="7"/>
    <eLiterals name="LESS" value="8"/>
    <eLiterals name="LESS_EQUALS" value="9"/>
    <eLiterals name="GREATER" value="10"/>
    <eLiterals name="GREATER_EQUALS" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//Case" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Case" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LetExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//LetBinding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LetBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Symbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//LogicValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicValue">
    <eLiterals name="UNKNOWN"/>
    <eLiterals name="FALSE" value="1"/>
    <eLiterals name="TRUE" value="2"/>
    <eLiterals name="ERROR" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyLiteral" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="CastExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetType" eType="#//Symbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregateExpression" abstract="true"
      eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="forallVariables" upperBound="-1"
        eType="#//Variable" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Count" eSuperTypes="#//AggregateExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregation" eSuperTypes="#//AggregateExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" eType="#//Symbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Forall" eSuperTypes="#//AggregateExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="forceObjectType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Symbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfinityLiteral" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interval" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerBound" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperBound" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Functor" abstract="true" eSuperTypes="#//Symbol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" abstract="true" eSuperTypes="#//Functor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaseRelation" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Predicate" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Datatype" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Function" abstract="true" eSuperTypes="#//Functor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultType" eType="#//Datatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metric" eSuperTypes="#//Function"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operator" eSuperTypes="#//Function"/>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//Symbol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="named" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAssertion" abstract="true" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctorDefiniton" abstract="true" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="head" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredicateDefinition" eSuperTypes="#//FunctorDefiniton #//InlinePredicateAttrributes"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDefinition" eSuperTypes="#//FunctorDefiniton">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultType" eType="#//Symbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Symbol"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//AttributeKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternDeclaration" abstract="true" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternFunctorDeclaration" abstract="true"
      eSuperTypes="#//ExternDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentList" eType="#//ArgumentList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternPredicateDeclaration" eSuperTypes="#//ExternFunctorDeclaration #//InlinePredicateAttrributes"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternFunctionDeclaration" eSuperTypes="#//ExternFunctorDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultType" eType="#//Symbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternAggregationOperatorDeclaration"
      eSuperTypes="#//ExternDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentType" eType="#//Symbol"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultType" eType="#//Symbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternDatatypeDeclaration" eSuperTypes="#//ExternDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDeclaration" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//Field" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertypes" upperBound="-1"
        eType="#//Symbol"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="root" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumDeclaration" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//EnumLiteral" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="crossReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//Symbol"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Symbol"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicity" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultAssertion" eSuperTypes="#//AbstractAssertion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assertion" eSuperTypes="#//AbstractAssertion"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnboundedMultiplicity" eSuperTypes="#//Multiplicity"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExactMultiplicity" eSuperTypes="#//Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoundedMultiplicity" eSuperTypes="#//Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InlinePredicateAttrributes" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="error" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregationOperator" eSuperTypes="#//Symbol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentType" eType="#//Datatype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultType" eType="#//Datatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Problem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbols" upperBound="-1"
        eType="#//Symbol" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedStarArgument" eSuperTypes="#//TypedArgument"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypedVariableArgument" eSuperTypes="#//TypedArgument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnnamedErrorPredicateDefintion" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentList" eType="#//ArgumentList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectiveDeclaration" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ObjectiveKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objective" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScopeDeclaration" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Symbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ObjectiveKind">
    <eLiterals name="MINIMIZATION"/>
    <eLiterals name="MAXIMIZATION" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExactScope" eSuperTypes="#//ScopeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoundedScope" eSuperTypes="#//ScopeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LowerBoundedScope" eSuperTypes="#//ScopeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespaceImport" eSuperTypes="#//Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UriImport" eSuperTypes="#//Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AttributeKind">
    <eLiterals name="FUNCTIONAL"/>
    <eLiterals name="ERROR" value="1"/>
    <eLiterals name="ROOT" value="2"/>
    <eLiterals name="CONTAINMENT" value="3"/>
  </eClassifiers>
</ecore:EPackage>
